### ISSUE TITLE
建议增加个“正常地图”的样式可选。

### ISSUE THREAD

**Issue by howlingFounts** [itorr/china-ex#14]
就是像这样子的
![中国地图](https://user-images.githubusercontent.com/43498546/196178708-8bab0fa4-39e2-45c8-a6f4-fb1eadf358a5.jpg)

**Comment by itorr** [comment]
@miklcct 写过一个这样的制县等级中国版可以去看看他的项目，地址在这里
https://github.com/miklcct/zhixian-dengji-zhongguo-ban
