### ISSUE TITLE
赶出来了一个美国版

### ISSUE THREAD

**Issue by tenpages** [itorr/china-ex#23]
之后有时间的话可能会修一修底图

https://tenpages.github.io/us-level/

**Comment by itorr** [comment]
ohhhh！妙呀 加到 Readme 了

**Comment by tenpages** [comment]
谢谢分享！有在考虑再做一个欧洲版的

**Comment by tenpages** [comment]
欧洲版coming right up
https://tenpages.github.io/us-level/eu.html
相应地美国版链接也修改了一下
https://tenpages.github.io/us-level/us.html

**Comment by Sys112358** [comment]
哥，美国版你的选词不太准确。两分那个alight是类似“经停”而且美国人都没见过这个词。“stayed”美国人会理解为过夜，并不是短暂居住。我打给我美国同学这个链接，他们表示十分疑惑哈哈哈

**Comment by tenpages** [comment]
Any suggestions?

我照搬了 https://zhung.com.tw/japanex/ 的英语版

**Comment by Sys112358** [comment]
我懂了，那就是中国版的那个把这几个level重新定义了一遍，没有按照日本那个标准来，你按照日本的这个来分级也可以的！只是alight这个词太不常见了，可以换成layover

**Comment by tenpages** [comment]
Cool. 之后会去修改一下。你可以在我那边开一个issue吗？如果不麻烦的话

**Comment by Likenttt** [comment]
请问这个svg是怎么做的?是用ai画出来的吗?相对位置是参考地图位置凭感觉手绘的吗还是有什么工具可以转化

**Comment by itorr** [comment]
> 请问这个svg是怎么做的?是用ai画出来的吗?相对位置是参考地图位置凭感觉手绘的吗还是有什么工具可以转化

我是 skwtch 起稿找特征，决定一个抽象程度之后 ai 细化

**Comment by tenpages** [comment]
> 请问这个svg是怎么做的?是用ai画出来的吗?相对位置是参考地图位置凭感觉手绘的吗还是有什么工具可以转化

我是在ai里手作的……用一个现成的地图当底图直接抽象去画
