### ISSUE TITLE
2022/10/21 编译报错

### ISSUE THREAD

**Issue by hackhu2019** [itorr/china-ex#38]
转译.js 107 行 `copyFileSync('html/样式.css','dist/样式.css');`  项目里文件名是 html/样式.less 应该保持文件名统一，否则 转译.js 执行报错

**Comment by itorr** [comment]
这里偷懒用 IDE 把 `样式.less` 转换成 `样式.css` 了，确实要补上

**Comment by itorr** [comment]
增加了 转译 less 成 css 的流程，现在 npm i; npm run build 就可以了
