### ISSUE TITLE
在执行'node 生成字体子集.js'的时候报错

### ISSUE THREAD

**Issue by MilkMilk233** [itorr/china-ex#41]
```
clone xxx
npm i
npm run build
```
在`npm run build`的时候报错，查证了一下好像是`node 生成字体子集.js`的时候报错了
OS: Ubuntu 20.04 LTS
Node Version: v10.19.0
npm Version: 6.14.4
Screen Shot:
![屏幕截图 2022-10-21 130702](https://user-images.githubusercontent.com/86474550/197116664-31755fb4-9bb7-411f-8323-7c96f7addf2e.jpg)

**Comment by itorr** [comment]
目测需要更新一下 ‘node’ 版本，或者尝试使用旧版本 ‘axios’ 包

**Comment by MilkMilk233** [comment]
Fixed, thanks!
