### ISSUE TITLE
npm run build 报错

### ISSUE THREAD

**Issue by conway2019** [itorr/china-ex#44]
Error: Cannot find module 'china-ex\生成字体子集.js;node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by yusancky** [comment]
> ![](https://user-images.githubusercontent.com/83524927/199259005-fa817a9a-ff14-443d-aea6-e345016b976e.png)

看得问题了吗？第一行加粗的模块名是不是明显不对？

**Comment by conway2019** [comment]
"build": "node 生成字体子集.js;node 转译.js"

**Comment by conway2019** [comment]
node 生成字体子集.js
node 转译.js
分成两个命令单独执行，可以了，谢谢！

**Comment by itorr** [comment]
奇怪，放一起居然会报错

**Comment by yusancky** [comment]
> 奇怪，放一起居然会报错。我这面一直没办法重现

我在本地搭建时也会出现同一错误。

难道是和操作系统有关系？

----

> node 生成字体子集.js
> node 转译.js
> 分成两个命令单独执行，可以了，谢谢！

我的解决方法是把 `;` 改成 `&&`，与分成两行等效。

[![](https://user-images.githubusercontent.com/83524927/201478351-7b4e04b5-449b-41fb-aa9a-7def41537ff8.png)](https://github.com/yusancky/GBA-ex/blob/2500d04f35c61b2fb4f05053b9758b348f7c5592/package.json#L6-L8)

**Comment by itorr** [comment]
> > 奇怪，放一起居然会报错。我这面一直没办法重现
> 
> 我在本地搭建时也会出现同一错误。
> 
> 难道是和操作系统有关系？
> 
> > node 生成字体子集.js
> > node 转译.js
> > 分成两个命令单独执行，可以了，谢谢！
> 
> 我的解决方法是把 `;` 改成 `&&`，与分成两行等效。
> 
> [![](https://user-images.githubusercontent.com/83524927/201478351-7b4e04b5-449b-41fb-aa9a-7def41537ff8.png)](https://github.com/yusancky/GBA-ex/blob/2500d04f35c61b2fb4f05053b9758b348f7c5592/package.json#L6-L8)

确实可能和操作系统有关，要不要 pull 过来ww
